/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dae2fd",
        background: "#f8f9ff",
        "on-secondary-fixed": "#001551",
        "on-surface-variant": "#45464d",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#0039b5",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "surface-container-high": "#dce9ff",
        secondary: "#1d4ed8",
        "on-error": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#bec6e0",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#271901",
        surface: "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#dec29a",
        "surface-tint": "#565e74",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#98805d",
        "inverse-on-surface": "#eaf1ff",
        primary: "#000000",
        "on-background": "#0b1c30",
        "tertiary-container": "#271901",
        "surface-variant": "#d3e4fe",
        "inverse-surface": "#213145",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "secondary-container": "#4069f2",
        "error-container": "#ffdad6",
        "primary-container": "#131b2e",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed-variant": "#574425",
        "secondary-fixed-dim": "#b7c4ff",
        "tertiary-fixed": "#fcdeb5",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#dce1ff",
        "outline-variant": "#c6c6cd",
        outline: "#76777d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "header-height": "3.25rem",
        "space-sm": "0.375rem",
        "table-row-dense": "2.25rem",
        "space-xl": "1.25rem",
        "space-lg": "1rem",
        "space-base": "0.75rem",
        "space-xs": "0.25rem",
        "space-md": "0.5rem",
        "table-row-default": "2.75rem",
        "space-3xl": "2rem",
        "sidebar-width": "15rem",
        "space-2xl": "1.5rem",
        "space-2xs": "0.125rem",
      },
      fontFamily: {
        display: ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        caption: ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "mono-data": ["Geist", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        display: ["30px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        caption: ["10px", { lineHeight: "12px", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.025em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "mono-data": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
